name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Container image
      run: docker build . --file Dockerfile --tag ghcr.io/naveensrinivasan/improved-invention:latest
    - uses: anchore/scan-action@v2
      id: scan
      with:
        image: "ghcr.io/naveensrinivasan/improved-invention:latest"
        acs-report-enable: true
    - name: upload Anchore scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
